language: groovy
jdk:
- openjdk7
addons:
  hosts:
  - grailsdbm
  hostname: grailsdbm
before_script:
- rm -rf build
script: ./travis-build.sh
env:
  global:
  - GIT_NAME="James Kleeh"
  - GIT_EMAIL="james.kleeh@gmail.com"
  - secure: bhWM+p4y19ktz2dikLhCa5HgQfwYTit6mMFqEv90xaBCwFFMhCvo0TNZwS/bAi/bpyS/m4VnVbdRd+VpNYzO50MYNXbfjwgHvApEH/93TNmyQtsVUjjrZBIGE398a8c1EJceUinq/T4IJECvqrB93N/50qpuqGBdi65ZHg6tr+8=
  - secure: rPGCJpgy/DL4pJrHdAcRioZRMhovh9hMYs0i9rDI+C9k0UK4ksciM4rrMUqgVJRnANQdjri+VOpuM7AlyISYtCfCu17C/SvVqayTWluNHUhHxD9lvW8WPE9iSBNLTRFvHnx43/+9/jcT4y5ikK9GjorBG9tDrZsmsgP8tjquTeE=
  - secure: h/PK5MLhCHIEtuhd+R/j8asUi48PlPUd25Qtxl29lkqhXQ7h/U6RySZxD4f9xKXB5M3x1vi0wJMxJ0K7tJdy315w/bK7wq6J9Zjd5EoVY5EOG4pgdYd6YMbUXT/41Ng7fIx39xuy5ZMhLWQORA9Jiq4TULGiFd0FPtQRtEbOmwc=
  - secure: a8kV4ZFoqhdRpKV1K0FqiNZwa/XHP6/vf+eTfIJxqehwHNVGJIiuGaU65hb2kyPF0HDHVSYyRl4O3Z+rzFgD1Rc4EtEXl0056JtMIcQzOEaHTo5nM4+tshieN8TFLTm0kpBORwjHsrBQ9VtUHLhnASKylBKTtHfdItGuzbWnrQM=
  - secure: maymdVzpsFfshzEd2Cx1Sl4kG+y2VStqBDQbFcvmuHtg98qS3kDkwUS+ss4Lie4WQGXG/S5ha7D+oY9ST0FV7u9lZZq34hno1/hHvQmv6YRX3+RV8mEH+RZk4ZbWug6IlqrdwbnFFRKhzBYtdNlIt+WdfFdnxFv7qgpw+MzbFGI=
