name: Java CI
on:
  push:
    branches:
      - githubactions
  pull_request:
    branches:
      - githubactions
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['1.8']
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Gradle
        run: ./gradlew clean check --parallel --continue
